AWSTemplateFormatVersion: "2010-09-09"

Resources:
  #Cloud9 Resource Setup
  Cloud9Env:
    Type: AWS::Cloud9::EnvironmentEC2
    Properties: 
      AutomaticStopTimeMinutes: 900
      Description: "tagging workshop cloud9 environment"
      ImageId: amazonlinux-2-x86_64
      InstanceType: m5.large
      Name: !Sub "${AWS::StackName}-env"
      Tags:
        - Key: component
          Value: compute
        - Key: tier
          Value: ide

Outputs:
     Cloud9DevEnvUrl:
       Description: Cloud9 Development Environment
       Value: !Sub "https://${AWS::Region}.console.aws.amazon.com/cloud9/ide/${Cloud9Env}"